### ISSUE TITLE
RFC 3392: Establishing the Leadership Council

### ISSUE THREAD

**Issue by weihanglo** [rust-tw/rfcs-tw#32]
We've got listed as one of the top 5 most used language based on the previous Rust annual survey. It's a good time for the Rust Taiwan Community to help the Rust project spread their words. 

This is an issue for the collaboration of the translation of [RFC 3392]. Given the RFC is not yet merged, I propose we pin our translation work on this specific commit, say rust-lang/rfcs@075f4b30f5c33315163c8e6a75e3210af6229ded (see #31). We can update it accordingly after it merges.

在去年 Rust 官方年度調查中，正體中文意外列入除英文外前五多 Rust 問卷調查回覆族群。Rust 台灣社群或許能協助 Rust 專案散播它的理念與想法。

此 issue 主要目的是 [RFC 3392] 的翻譯協作。由於該 RFC 尚未合併，我提議翻譯先從一個固定 commit 出發，例如 rust-lang/rfcs@075f4b30f5c33315163c8e6a75e3210af6229ded（參見 #31），RFC 合併之後再視情況更新。

---

I am going to list each section here. If anyone wants to help translate one, leave a comment here and someone will assign it to you. Hope we won't get too many merge conflicts. Thank you!

The file to translate [is here].

若您願意協助翻譯，為避免合併衝突，請在 issue 底下留言，例如：「**我想協助翻譯『摘要』一節**」，我們會協助標註在此列表中。感謝！

欲翻譯的文件[在此][is here]。

[RFC 3392]: https://github.com/rust-lang/rfcs/pull/3392
[is here]: https://github.com/rust-tw/rfcs-tw/blob/zh_tw/text/3392-leadership-council.md

- [ ] Summary 摘要 @TSOTSI1 #40
- [x] Outline 大綱 @weihanglo #33
- [x] Reference materials 參考資料 @weihanglo #44
- [ ] Motivation 動機 @TSOTSI1 #40
- [x] Duties, expectations, and constraints on the Council 理事會之職責、期待與限制 @dklassic #34
- [x] Structure of the Council 理事會組織架構 @dklassic #34
  - [x] Top-level teams 一級團隊單位 @dklassic #34
    - [x] Initial list of top-level teams 一級團隊初始名單 @dklassic #34
    - [x] The "launching pad" top-level team 「啟動台」 一級團隊 @dklassic #34
    - [x] Removing top-level teams 廢除一級團隊 @dklassic #34
  - [x] Alternates and forgoing representation 候補與放棄代表權利 @weihanglo #45
  - [x] Term limits 任期限制 @kazanV #35
  - [x] Limits on representatives from a single company/entity 對單一公司或實體代表之限制  @weihanglo #47
  - [x] Candidate criteria 候選資格 @weihanglo #38
  - [ ] Relationship to the core team 與 Core 團隊之關係 @kazanV #46
  - [ ] Relationship to the Rust Foundation 與 Rust 基金會之關係 @kazanV #46
- [x] The Council's decision-making process 理事會決策流程 @dklassic #48
  - [x] Operational vs policy decisions 營運與政策決策
  - [x] Repetition and exceptions 重複與例外
  - [x] The consent decision-making process 共識決策流程
    - [x] Approval criteria 核准標準
  - [x] Modifying and tuning the decision-making process 變更與調整決策流程
  - [x] Agenda and backlog 議程與待辦事項
  - [x] Deadlock resolution 解決僵局
  - [x] Feedback and evaluation 回饋與評估
- [x] Transparency and oversight for decision making 決策流程之透明度和監督 @dklassic #41
  - [x] Decisions that the Council may make internally 理事會可在內部做出之決策 @dklassic #41
  - [x] Decisions that the Council must necessarily make privately 理事會須私下保密做出之決策 @dklassic #41
  - [x] Decisions that the Council must make via public proposal 理事會須經公開提案做出之決策 @dklassic $41
  - [x] Conflicts of interest 利益衝突 @dklassic #41
  - [x] Determining and changing team purviews 確定與更改團隊權責 @dklassic #41
- [x] Mechanisms for oversight and accountability 監督與問責機制 @dklassic #43
  - [x] Ensuring the Council is accountable 確保能追究理事會之責任 @dklassic #43
  - [x] Ensuring Council representatives are accountable 確保能追究理事會代表之責任 @dklassic #43
  - [x] Ensuring teams are accountable 確保能追究團隊之責任 @dklassic #43
- [x] Moderation, disagreements, and conflicts 審核、分歧與衝突 @dklassic #49
  - [x] Disagreements among teams 團隊間之分歧 
  - [x] Conflicts involving teams or Project members 涉及團隊或專案成員之衝突 
  - [x] Contingent moderators 審核人代表團
  - [x Moderation team policies and procedures 審核團隊之政策與程序
  - [x] Audits 稽核
  - [x] Last-resort accountability 最終問責機制
  - [x] Moderation actions involving Project members 涉及專案成員之審核措施
  - [x] Conflicts involving Council representatives 涉及理事會代表之衝突
  - [x] Conflicts involving moderation team members 涉及審核團隊成員之衝突
- [x] Ratification of this RFC 本案之批准 @weihanglo #37
- [ ] Footnotes 附註 @kazanV

**Comment by ericsampson** [comment]
<3

**Comment by BenzaSattva** [comment]
我想協助翻譯『摘要, 動機』兩節 先認領這兩節 等翻譯完後繼續協助後續 感謝

**Comment by kazanTW** [comment]
我想先協助翻譯「任期限制」一節

**Comment by dklassic** [comment]
我想先協助翻譯「理事會之職責、期待與限制」、「理事會組織架構」、「一級團隊單位」、「一級團隊初始名單」、「「啟動台」 一級團隊」、「廢除一級團隊」以及「決策流程之透明度和監督」整章（包含「理事會可在內部做出之決定」、「理事會須私下保密做出之決定」、「理事會須經公開提案做出之決定」、「利益衝突」、「確定與更改團隊權責」）

「理事會之職責、期待與限制」、「理事會組織架構」、「一級團隊單位」、「一級團隊初始名單」、「「啟動台」 一級團隊」、「廢除一級團隊」其實我已經先翻譯完了（掩面

**Comment by dklassic** [comment]
看看應該還有時間，我可以再翻一章！
我想協助翻譯 「監督與問責機制」、「確保能追究理事會之責任」、「確保能追究理事會代表之責任」、「確保能追究團隊之責任」

**Comment by kazanTW** [comment]
我想繼續協助翻譯「與 Core 團隊之關係」、「與 Rust 基金會之關係」、「附註」

**Comment by weihanglo** [comment]
我想協助翻譯「審核、分歧與衝突」、「團隊間之分歧」、「涉及團隊或專案成員之衝突」與「審核人代表團」。

**Comment by kazanTW** [comment]
另外，我想提議將 "Core" 統一翻譯為「核心」

**Comment by kazanTW** [comment]
然後提供一下這份工作指引作為參考：
https://hackmd.io/@l10n-tw/translation_guidelines#%E5%8D%94%E8%AA%BF

**Comment by dklassic** [comment]
> 另外，我想提議將 "Core" 統一翻譯為「核心」

原本是翻核心團隊沒錯，是因為我在 #34 發現現在 rust-lang.org 正體中文翻譯中將 Core 省略不翻譯。
@weihanglo 提到說官網翻譯現在改不了所以現在才暫時一致維持 Core 團隊 XD

**Comment by kazanTW** [comment]
原來如此w
另外關於 institutional memory 我暫時翻為機構記憶，但我正在尋求更精確的譯文

**Comment by dklassic** [comment]
@weihanglo 如果還需要幫忙的話，我這週末可以翻完剩下的 RFC 內容「理事會決策流程」和「審核、分歧與衝突」。
因為已經有部分內容先預標註 ID 了，想先確認清楚還有沒有翻譯需求以及具體來說還需要哪些部分～

**Comment by weihanglo** [comment]
@dklassic feel free to take over

因為我的前兩支 PR 還沒 review，所以就沒繼續翻譯其他章節了 😂

**Comment by dklassic** [comment]
@weihanglo 那我就接收這兩段了，週末翻一翻！
